const questionsData = [
  // FRIENDS Category (20 questions)
  { text: "What's the most embarrassing thing you've done in front of your friends?", category: "Friends" },
  { text: "If you could swap lives with one friend for a day, who would it be and why?", category: "Friends" },
  { text: "What's a secret talent none of your friends know about?", category: "Friends" },
  { text: "Describe your perfect friend hangout day from start to finish.", category: "Friends" },
  { text: "What's the funniest inside joke you share with your friends?", category: "Friends" },
  { text: "If your friend group was a TV show, what would it be called?", category: "Friends" },
  { text: "What's the worst advice a friend has ever given you?", category: "Friends" },
  { text: "Which friend would survive the longest in a zombie apocalypse and why?", category: "Friends" },
  { text: "What's something you've always wanted to tell your friends but never did?", category: "Friends" },
  { text: "If you had to be stuck on a deserted island with one friend, who would you choose?", category: "Friends" },
  { text: "What's the craziest adventure you've had with your friends?", category: "Friends" },
  { text: "Which friend is most likely to become famous and for what?", category: "Friends" },
  { text: "What's a habit of yours that annoys your friends the most?", category: "Friends" },
  { text: "If you could give your friend group a superpower, what would it be?", category: "Friends" },
  { text: "What's the best gift a friend has ever given you?", category: "Friends" },
  { text: "Describe your first impression of your closest friend.", category: "Friends" },
  { text: "What's a memory with your friends that always makes you laugh?", category: "Friends" },
  { text: "If your friends had to describe you in three words, what would they say?", category: "Friends" },
  { text: "What's something you learned about yourself through your friendships?", category: "Friends" },
  { text: "What's the longest you've gone without talking to your best friend and why?", category: "Friends" },

  // DATE Category (20 questions)
  { text: "What's your idea of a perfect first date?", category: "Date" },
  { text: "What's the most romantic thing you've ever done for someone?", category: "Date" },
  { text: "What quality do you find most attractive in a person?", category: "Date" },
  { text: "Describe your dream vacation with your significant other.", category: "Date" },
  { text: "What's a deal-breaker for you in a relationship?", category: "Date" },
  { text: "What's the cheesiest pickup line you've ever used or heard?", category: "Date" },
  { text: "If we could travel anywhere together right now, where would you want to go?", category: "Date" },
  { text: "What's something you've never told anyone about your romantic life?", category: "Date" },
  { text: "What song reminds you of your favorite romantic memory?", category: "Date" },
  { text: "What's your love language?", category: "Date" },
  { text: "Describe your perfect Sunday morning with your partner.", category: "Date" },
  { text: "What's the most adventurous date you've ever been on?", category: "Date" },
  { text: "What's a small gesture that makes you feel loved?", category: "Date" },
  { text: "If you could cook one meal for your date, what would it be?", category: "Date" },
  { text: "What's the best compliment you've ever received?", category: "Date" },
  { text: "What's something quirky about yourself that you hope your partner finds endearing?", category: "Date" },
  { text: "What's your biggest fear when it comes to relationships?", category: "Date" },
  { text: "If you could relive one romantic moment, which would it be?", category: "Date" },
  { text: "What's the most important lesson you've learned from past relationships?", category: "Date" },
  { text: "What does commitment mean to you?", category: "Date" },

  // FAMILY Category (20 questions)
  { text: "What's your favorite family tradition?", category: "Family" },
  { text: "What's the funniest thing that happened at a family gathering?", category: "Family" },
  { text: "Which family member are you most similar to and why?", category: "Family" },
  { text: "What's a family recipe that's been passed down through generations?", category: "Family" },
  { text: "What's the best advice a family member has given you?", category: "Family" },
  { text: "Describe your favorite childhood memory with your family.", category: "Family" },
  { text: "If you could have dinner with any ancestor, who would it be?", category: "Family" },
  { text: "What's something your parents taught you that you'll always carry with you?", category: "Family" },
  { text: "What family vacation was the most memorable and why?", category: "Family" },
  { text: "What's a funny nickname someone in your family has?", category: "Family" },
  { text: "If your family was a sitcom, what would be the running joke?", category: "Family" },
  { text: "What's a skill or hobby that runs in your family?", category: "Family" },
  { text: "What's the most valuable thing you've inherited from your family?", category: "Family" },
  { text: "Describe your family in three words.", category: "Family" },
  { text: "What's a family secret that everyone knows but no one talks about?", category: "Family" },
  { text: "What's the biggest sacrifice a family member made for you?", category: "Family" },
  { text: "If you could change one thing about your family dynamics, what would it be?", category: "Family" },
  { text: "What's something you appreciate about your family now that you didn't before?", category: "Family" },
  { text: "What tradition would you want to pass on to future generations?", category: "Family" },
  { text: "What's the most important value your family instilled in you?", category: "Family" },

  // DEEP Category (20 questions)
  { text: "What's your biggest regret and what did you learn from it?", category: "Deep" },
  { text: "If you could change one decision from your past, what would it be?", category: "Deep" },
  { text: "What do you think is the meaning of life?", category: "Deep" },
  { text: "What's a belief you held strongly that changed over time?", category: "Deep" },
  { text: "What legacy do you want to leave behind?", category: "Deep" },
  { text: "What's your biggest fear that you rarely talk about?", category: "Deep" },
  { text: "If you knew you had one year to live, what would you do differently?", category: "Deep" },
  { text: "What's something about yourself you're still trying to understand?", category: "Deep" },
  { text: "What does success mean to you?", category: "Deep" },
  { text: "What's a question you wish someone would ask you?", category: "Deep" },
  { text: "What's the hardest truth you've had to accept about yourself?", category: "Deep" },
  { text: "If you could send a message to your younger self, what would it be?", category: "Deep" },
  { text: "What experience fundamentally changed who you are?", category: "Deep" },
  { text: "What do you think happens after we die?", category: "Deep" },
  { text: "What's the most valuable lesson failure has taught you?", category: "Deep" },
  { text: "If you could know the absolute truth about one thing, what would you want to know?", category: "Deep" },
  { text: "What's something you pretend to understand but actually don't?", category: "Deep" },
  { text: "What would you do if you knew you couldn't fail?", category: "Deep" },
  { text: "What does happiness look like to you?", category: "Deep" },
  { text: "What's a moment when you felt truly at peace?", category: "Deep" },

  // FUNNY Category (20 questions)
  { text: "What's the most ridiculous thing you've ever done to impress someone?", category: "Funny" },
  { text: "If you were a superhero, what would be your useless superpower?", category: "Funny" },
  { text: "What's the weirdest food combination you secretly enjoy?", category: "Funny" },
  { text: "If your life was a meme, which one would it be?", category: "Funny" },
  { text: "What's the most embarrassing song on your playlist?", category: "Funny" },
  { text: "If you could be any kitchen appliance, which would you be and why?", category: "Funny" },
  { text: "What's the dumbest way you've ever injured yourself?", category: "Funny" },
  { text: "If animals could talk, which would be the rudest?", category: "Funny" },
  { text: "What's something you're terrible at but love doing anyway?", category: "Funny" },
  { text: "If you had to eat one food for the rest of your life, what would it be?", category: "Funny" },
  { text: "What's the strangest dream you've ever had?", category: "Funny" },
  { text: "If you could be famous for something stupid, what would it be?", category: "Funny" },
  { text: "What's the worst fashion choice you've ever made?", category: "Funny" },
  { text: "If your pet could talk for one minute, what do you think it would say about you?", category: "Funny" },
  { text: "What's the most useless skill you have?", category: "Funny" },
  { text: "If you were arrested for something, what would everyone assume it was for?", category: "Funny" },
  { text: "What's the weirdest thing you've ever googled?", category: "Funny" },
  { text: "If you had to wear a costume for the rest of your life, what would it be?", category: "Funny" },
  { text: "What's the most ridiculous lie you've ever told that people believed?", category: "Funny" },
  { text: "If you could make one rule everyone had to follow, what would it be?", category: "Funny" }
];

module.exports = questionsData;
